server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
