version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=tasks
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 12

  flyway:
    container_name: flyway
    depends_on:
      mysql:
        condition: service_healthy
    image: flyway/flyway:9-alpine
    volumes:
      - ./infrastructure/src/main/resources/db/migration:/flyway/sql:ro
    environment:
      - FLYWAY_URL=jdbc:mysql://mysql:3306/tasks?allowPublicKeyRetrieval=true
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=root123
    command: [ "migrate" ]

  app:
    container_name: app
    depends_on:
      mysql:
        condition: service_healthy
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - MYSQL_URL=mysql:3306/tasks
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root123
      - JWT_ISSUER=https://dev-j6pmr0ckitt2062o.us.auth0.com/
      - JWT_JWKS=https://dev-j6pmr0ckitt2062o.us.auth0.com/.well-known/jwks.json
    ports:
      - "8080:8080"
