version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=tasks
    ports:
      - "3306:3306"

  task:
    container_name: task
    build: .
    profiles:
      - app
    environment:
      - MYSQL_URL=mysql:3306
    depends_on:
      - mysql
    ports:
      - "8080:8080"
