name: CD Pipeline

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Run Tests
        run: ./gradlew test
  build:
    name: Build Runner
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Run Build
        run: ./gradlew bootJar
  deploy:
    name: Deploy Runner
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Image Version
        run: |
          echo IMAGE_VERSION=$(echo ${{ github.ref_name }} | sed "s/^release\///") >> $GITHUB_ENV
          echo "Image Version - $IMAGE_VERSION"
      - name: Push Image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.IMAGE_VERSION }}
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.IMAGE_VERSION }}
